version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:5.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

